### PR TITLE
Smarter swtch

### PR DESCRIPTION
**Pull request by philhofer**
Makes arm context switch >10% faster. Also, cleans up some random whitespace.

@bwross

---
This change is [Reviewable](https://reviewable.io/reviews/philhofer/chip/15)

### CODE REVIEW

**Comment by bwross** [comment]
*[src/runtime.c, line 26 \[r1\]](https://reviewable.io:443/reviews/philhofer/chip/15#-KGcAt6Tmd-v1gxsNPPs:-KGcAt6Tmd-v1gxsNPPt:-2114729668) ([raw file](https://github.com/philhofer/chip/blob/14312ab3db538f9e7afa1617352a1f223c081fc1/src/runtime.c#L26)):*
Comma after "setup()".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/philhofer/chip/15)*

**Comment by bwross** [comment]
*[src/runtime.c, line 162 \[r1\]](https://reviewable.io:443/reviews/philhofer/chip/15#-KGcEc4irVEMyHpN_Lu7:-KGcEc4irVEMyHpN_Lu8:821303326) ([raw file](https://github.com/philhofer/chip/blob/14312ab3db538f9e7afa1617352a1f223c081fc1/src/runtime.c#L162)):*
No idea how often this is called, nor whether this would be any faster:
```
do {
  v = arena->bits[i];
} while (v == ~0 && ++i < BITMAP_WORDS);

int bit = __builtin_ffsl(~v)-1;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/philhofer/chip/15)*

**Comment by philhofer** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/runtime.c, line 162 \[r1\]](https://reviewable.io:443/reviews/philhofer/chip/15#-KGcEc4irVEMyHpN_Lu7:-KGcIjl5RQ2ZZGjdjnlC:-855053776) ([raw file](https://github.com/philhofer/chip/blob/14312ab3db538f9e7afa1617352a1f223c081fc1/src/runtime.c#L162)):*
This is in the stack-allocation path, so it is called relatively frequently.

From the disassembly it looks like gcc knows that these are really the same thing. I benchmarked it on my laptop and on an arm board to be sure, but the results are indistinguishable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/philhofer/chip/15)*

**Comment by bwross** [comment]
*[src/runtime.c, line 26 \[r1\]](https://reviewable.io:443/reviews/philhofer/chip/15#-KGcAt6Tmd-v1gxsNPPs:-KGcP8-SGqbKM3Jz0kO1:850319070) ([raw file](https://github.com/philhofer/chip/blob/14312ab3db538f9e7afa1617352a1f223c081fc1/src/runtime.c#L26)):*
All in the world is now right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/philhofer/chip/15)*

**Comment by bwross** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/philhofer/chip/15)*

**Pull request merged**
