### PR TITLE
Add support for asan

### PR DESCRIPTION
**Pull request by philhofer**
This adds support for AddressSanitizer in gcc and clang by teaching the sanitizer about which stacks are valid. On platforms that don't support AddressSanitizer, use `mprotect` instead. (That produces less friendly output, but at least you'll catch the bugs.)

The only weirdness in the scheduler is that we have to poison a free'd stack after the first context switch off of that stack in order to avoid poisoning the running stack.

@bwross @codemac

[Review on Reviewable](https://reviewable.io/reviews/philhofer/chip/13)

### CODE REVIEW

**Comment by philhofer** [comment]
Tying up loose ends:

- [ ] Use `mprotect` in debug builds when address sanitizer isn't supported
- [ ] Don't use LeakSanitizer on OSX (it only works on linux-amd64)
- [ ] Move sanitizer headers from `include` into `src/sanitizer/...`
- [ ] Clean up as much macro nonsense as possible

**Comment by bwross** [comment]
*[src/runtime_epoll.h, line 3 \[r3\]](https://reviewable.io:443/reviews/philhofer/chip/13#-KAHrVwbVZNGI_AUR-Tm:-KAHrVwcxYmfoQpqdWNM:1375235085) ([raw file](https://github.com/philhofer/chip/blob/58f3f4b131a22c75f99395ec0374946bdcfc9d9b/src/runtime_epoll.h#L3)):*
?!?!?!?!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/philhofer/chip/13)*

**Comment by bwross** [comment]
Reviewed 2 of 17 files at r1, 14 of 16 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/sanitizer.h, line 1 \[r3\]](https://reviewable.io:443/reviews/philhofer/chip/13#-KAHs5wPXCvW7xsuI94w:-KAHs5wPXCvW7xsuI94x:866682338) ([raw file](https://github.com/philhofer/chip/blob/58f3f4b131a22c75f99395ec0374946bdcfc9d9b/src/sanitizer.h#L1)):*
Please remove this whitespace if you do not remove this file.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/philhofer/chip/13)*

**Comment by philhofer** [comment]
@bwross PTAL

**Comment by philhofer** [comment]
Review status: 15 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/runtime_epoll.h, line 3 \[r3\]](https://reviewable.io:443/reviews/philhofer/chip/13#-KAHrVwbVZNGI_AUR-Tm:-KAIrAQLPxf6mbK4clvD:-1595770471) ([raw file](https://github.com/philhofer/chip/blob/58f3f4b131a22c75f99395ec0374946bdcfc9d9b/src/runtime_epoll.h#L3)):*
(You need to manually mark this as resolved, since you marked it as blocking.)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/philhofer/chip/13)*

**Comment by bwross** [comment]
Review status: 15 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/runtime_epoll.h, line 3 \[r3\]](https://reviewable.io:443/reviews/philhofer/chip/13#-KAHrVwbVZNGI_AUR-Tm:-KALkWIj4aDM5muSRxL6:-495874704) ([raw file](https://github.com/philhofer/chip/blob/58f3f4b131a22c75f99395ec0374946bdcfc9d9b/src/runtime_epoll.h#L3)):*
I am satisfied with this change.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/philhofer/chip/13)*

**Comment by bwross** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/philhofer/chip/13)*

**Pull request merged**
